#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType specie
wmake $targetType thermophysicalProperties

if isMinGW; then
    hackThisHeader="specie/lnInclude/linear.H"
    
    if ! grep -q -e "FINITE_VOLUME_LOAD" $hackThisHeader
    then
        mv $hackThisHeader ${hackThisHeader}.tmp && \
        (
            echo "#ifndef FINITE_VOLUME_LOAD" > $hackThisHeader
            cat ${hackThisHeader}.tmp >> $hackThisHeader
            echo "#else" >> $hackThisHeader
            echo "#include_next \"linear.H\"" >> $hackThisHeader
            echo "#endif" >> $hackThisHeader
        )
    fi
fi

wmake $targetType basic
wmake $targetType multicomponentThermo
wmake $targetType laminarFlameSpeed
wmake $targetType chemistryModel

wmake $targetType solidThermo

wmake $targetType saturationModels

wmake $targetType ignition

#------------------------------------------------------------------------------
