#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType specie
wmake $targetType thermophysicalProperties

if isMinGW; then
    wmakeMinGWPatchHeader2Next specie/lnInclude/linear.H FINITE_VOLUME_LOAD
fi

wmake $targetType basic
wmake $targetType multicomponentThermo
wmake $targetType laminarFlameSpeed
wmake $targetType chemistryModel

wmake $targetType solidThermo

wmake $targetType saturationModels

wmake $targetType ignition

#------------------------------------------------------------------------------
