#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

if isMinGW
then

    EXTRA_OPTIONS_FILE="Make/extraOptions"
    echo 'EXE_LIBS += \' > $EXTRA_OPTIONS_FILE

    # We have to collect the list of libraries that exist in $FOAM_LIBBIN for
    # listing options there-in
    find $FOAM_LIBBIN -name "*.dll" -printf '%f\n' | \
        sort -u | \
        sed -e 's=^lib==' -e 's=\.dll$==' | \
        grep -v -e '^OpenFOAM$' \
                -e '^Pstream$' \
                -e '^MGridGen$' \
                -e '^compressibleTurbulenceModels$' \
                -e '^incompressibleTurbulenceModels$' \
                -e '^finiteVolume$' \
                -e '^stubLibrary$' \
                -e '^userd-foam$' | \
        sed -e 's=^= -l=' -e 's=$= \\=' \
            >> $EXTRA_OPTIONS_FILE
    
    # Remove last line break escape character
    sed -i -e '$s= \\$==' $EXTRA_OPTIONS_FILE

    unset EXTRA_OPTIONS_FILE

fi

wmake

#------------------------------------------------------------------------------
