#                            -*- mode: org; -*-
#
#+TITLE:          blueCFD-Core README for version 2.3-x
#+AUTHOR:                      blueCAPE Lda
#+DATE:                       13th July 2016
#+LINK:                  http://bluecfd.com/Core
#+OPTIONS: author:nil ^:{}
# Copyright (c) 2013-2016 blueCAPE Lda.

* About blueCFD-Core
  blueCFD®-Core is a service package provided by blueCAPE Lda, of a high
  quality build version of OpenFOAM® for up-to-date Windows 7 to 10, all 64bit,
  with some additional tweaks, executables and scripts, in order to maintain
  usability under a Windows environment.
  Building for 32 bit and/or running on Windows XP and Vista should be
  possible, but it's no longer supported.

  OpenFOAM is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  See the file =COPYING= in this directory or
  [[http://www.gnu.org/licenses/]], for a description of the GNU General Public
  License terms under which you can copy the files.
  
  More information about OpenFOAM is provided in the file =README.OpenFOAM.org=

* Information
  This source code is a patched version of the original OpenFOAM source code.
  The modifications made are tracked at the blueCFD project at Github:
      [[http://github.com/blueCFD]]

  The modifications made for the blueCFD-Core project are based on Symscape's
  modifications to the OpenFOAM source code, which are provided at their
  website: [[http://www.symscape.com]]

* Disclaimer
  blueCAPE Lda is responsible for blueCFD®-Core. blueCAPE Lda is in no way
  associated with OpenCFD (ESI Group), nor holds any copyrights over OpenFOAM®.
  This offering is not approved or endorsed by OpenCFD (ESI Group), the
  producer of the OpenFOAM software and owner of the OPENFOAM® and OpenCFD®
  trade marks.

* Project page
  [[http://bluecfd.github.io/Core/]]

* Release notes
  [[http://joomla.bluecape.com.pt/files/news/blueCFD-ReleaseNotes-2.3.pdf]]

* Documentation
  [[https://github.com/blueCFD/Core/wiki]]

* Support and development contracts related to blueCFD
  [[http://bluecfd.com/contact]]

* Reporting Bugs in blueCFD
  [[https://github.com/blueCFD/Core/issues]]
