#!/bin/sh
#------------------------------------------------------------------------------
# 2016-07-18/19 blueCAPE Lda: Modifications for blueCFD-Core 2016-1
#------------------------------------------------------------------------------
# License
#     This file is a derivative work of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Modifications
#     This file has been modified by blueCAPE's unofficial mingw patches for
#     OpenFOAM.
#     For more information about these patches, visit:
#         http://bluecfd.com/Core
#
#     Modifications made:
#        - This script will reinterpret the paths for a single object file
#          from the MSys2 path to Windows long paths
#
# Script
#     makeFileLongPath
#
# Description
#     Translates the file path, but only on Windows.
#
#------------------------------------------------------------------------------

CYGPATH_EXTRA=
MUST_FIT=

if [ "$1" = "-fit" ]
then
    shift
    MUST_FIT=yes
fi

if onWin
then

    if [ -n "${MUST_FIT}" ]
    then
        FULL_PATH=$(cygpath -a -w -m "${1}" | sed -e 's=^//?/=\\\\?\\=')
        CHAR_COUNT=$(echo "${FULL_PATH}" | wc -m)
        if [ $CHAR_COUNT -gt 259 ]
        then
            CYGPATH_EXTRA="-s"
            touch "${FULL_PATH/^\\\\\?\\/}"
        fi
    fi

    cygpath -a $CYGPATH_EXTRA -w -m "${1}" | sed 's=\\=\\\\=g'

else

    echo $1

fi

#------------------------------------------------------------------------------
