#!/bin/sh
#------------------------------------------------------------------------------
# 2016-07-15 blueCAPE Lda: Modifications for blueCFD-Core 2016-1
# 2016-202X FS Dynamics Portugal: Subsequent changes are tracked at:
#       https://github.com/blueCFD/OpenFOAM-dev
#------------------------------------------------------------------------------
# License
#     This file is a derivative work of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Modifications
#     This file has been modified by blueCAPE's unofficial mingw patches for
#     OpenFOAM.
#     For more information about these patches, visit:
#         http://bluecfd.com/Core
#
#     Modifications made:
#        - This script will reinterpret the paths for the object files from
#          the MSys2 path to Windows paths
#        - Technically this is not needed on Linux, unless OpenFOAM's object
#          list shoots up to twice as many in the future.
#
# Script
#     makeReinterpretObjectPaths
#
# Description
#     Constructs the object path list.
#
#------------------------------------------------------------------------------

Script=${0##*/}
ScriptFolder=${0%/*}


objectListPath=$1
shift

if [ -e "${objectListPath}" ]
then
    rm "${objectListPath}"
fi

touch "${objectListPath}"

if onWin
then

    for object in $@
    do

      ${ScriptFolder}/makeFileLongPath -fit $object >> "${objectListPath}"

    done

else

    for object in $@
    do

      echo $object >> "${objectListPath}"

    done

fi

#------------------------------------------------------------------------------
