#!/bin/sh
#------------------------------------------------------------------------------
# 2017-09-04 blueCAPE Lda: Modifications for blueCFD-Core 2016-2
#------------------------------------------------------------------------------
# License
#     This file is a derivative work of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Modifications
#     This file has been modified by blueCAPE's unofficial mingw patches for
#     OpenFOAM.
#     For more information about these patches, visit:
#         http://bluecfd.com/Core
#
#     Modifications made:
#        - This script will reinterpret the paths for a single object file
#          from the current path to a specific temporary path
#
# Script
#     makeTemporaryObjectPath
#
# Description
#     First argument is the main object folder, second argument is the file to
#     be temporarily here.
#
#------------------------------------------------------------------------------

if [ $# -eq 2 ]
then

    fileName=$(basename $2)

    if [ "$1/$fileName" = "$2" ]
    then
        echo $2
    else
        echo $1/tempDir/$fileName
    fi

fi

#------------------------------------------------------------------------------
