#!/bin/sh
#------------------------------------------------------------------------------
# 2016-12-07 blueCAPE Lda: Moved functionality from makeVersionResourceFile
# 2016-202X FS Dynamics Portugal: Subsequent changes are tracked at:
#       https://github.com/blueCFD/OpenFOAM-dev
#------------------------------------------------------------------------------
# License
#     This file is a derivative work of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Modifications
#     This file has been created by blueCAPE's unofficial mingw patches for
#     OpenFOAM.
#     For more information about these patches, visit:
#         http://bluecfd.com/Core
#
#     Modifications made:
#        - This script was the result of dividing makeVersionResourceFile into
#          3, so that each file can be updated by the rule files accordingly.
#
# Script
#     makeVersionResourceDepFile
#
# Description
#     Constructs the dependency file for the version resource file.
#
#------------------------------------------------------------------------------

# Provided by makefiles/files
OBJECTS_DIR=$1
VERSIONFILE=$2
DEPFILE=$3

# Change to the $OBJECTS_DIR directory
if [ ! -d "$OBJECTS_DIR" ]
then
    echo "Could not use the directory '$OBJECTS_DIR'" 1>&2
    exit 1
fi

# Plug in the version resource file for being compiled along
FILE_NAMEwEXT=${VERSIONFILE##*/}
FILE_NAME=${FILE_NAMEwEXT%%.rc}

# Purge previous .dep file
if [ -e "$DEPFILE" ]
then
    rm -r $DEPFILE
fi

# Create custom made dep file
touch ${VERSIONFILE}.dep
echo '$(OBJECTS_DIR)/'$FILE_NAMEwEXT'.dep: $(OBJECTS_DIR)/'$FILE_NAMEwEXT \
     > $DEPFILE
echo '' >> $DEPFILE
echo '$(OBJECTS_DIR)/'$FILE_NAME'.o : $(OBJECTS_DIR)/'$FILE_NAMEwEXT \
     >> $DEPFILE
echo '	$(rctoo)' >> $DEPFILE


#------------------------------------------------------------------------------
