#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmakeCheckPwd "$WM_PROJECT_DIR/applications" || {
    echo "Allwmake error: Current directory is not \$WM_PROJECT_DIR/applications"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

set -x

wmake -all utilities $*
wmake -all solvers $*


if isMinGW; then

  # Test-parallel, because MPi on Windows can be rather finicky
  wmake -all test/parallel

  wmakeVerifyExeDependencies utilities || wmake -all utilities
  wmakeVerifyExeDependencies solvers || wmake -all solvers

  # Redo Test-parallel, to sort out for missing dependencies
  wmakeVerifyExeDependencies test/parallel || wmake -all test/parallel
fi

# ----------------------------------------------------------------- end-of-file
