#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmakeCheckPwd "$WM_PROJECT_DIR/applications" || {
    echo "Allwmake error: Current directory is not \$WM_PROJECT_DIR/applications"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

set -x

wmake -all utilities $*
wmake -all solvers $*


if isMinGW; then

  #ccm26ToFoam - use a containment shell since it depends on license.
  ( set +e; wmake -all utilities/mesh/conversion/Optional ; exit 0 )

  #Test-parallel  
  wmake -all test/parallel

  wmakeVerifyExeDependencies utilities || wmake -all utilities
  wmakeVerifyExeDependencies solvers || wmake -all solvers

  #ccm26ToFoam - use a containment shell since it depends on license.
  ( set +e; wmake all utilities/mesh/conversion/Optional ; exit 0 )

  #Test-parallel
  wmakeVerifyExeDependencies test/parallel || wmake -all test/parallel
fi

# ----------------------------------------------------------------- end-of-file
