#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
targetType=lib
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments $*

unset COMP_FLAGS LINK_FLAGS

# make library (static by default)
wmake $targetType

# ----------------------------------------------------------------- end-of-file
