#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wmake -all blockMesh
wmake -all extrude
wmake -all extrude2DMesh
wmake -all snappyHexMesh

if [ -n "$CGAL_ARCH_PATH" ]
then
    foamyMesh/Allwmake
fi


# ----------------------------------------------------------------- end-of-file
