#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake all blockMesh
wmake all extrude
wmake all extrude2DMesh
wmake all snappyHexMesh

wmake all foamyHexMesh
wmake all foamyQuadMesh


# ----------------------------------------------------------------- end-of-file
