#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

if isMinGW; then
    wmakeLnInclude interRegion

    wmakeMinGWPatchHeader2Next interRegion/lnInclude/variable.H INTER_REGION_VAR
fi


wmake $targetType general
wmake $targetType interRegion
wmake $targetType rotorDisk
#wmake $targetType propellerDisk

#------------------------------------------------------------------------------
