#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

if isMinGW; then
    wmakeLnInclude interRegion
    hackThisHeader="interRegion/lnInclude/variable.H"
    
    if ! grep -q -e "INTER_REGION_VAR" $hackThisHeader
    then
        mv $hackThisHeader ${hackThisHeader}.tmp && \
        (
            echo "#ifdef INTER_REGION_VAR" > $hackThisHeader
            cat ${hackThisHeader}.tmp >> $hackThisHeader
            echo "#else" >> $hackThisHeader
            echo "#include_next \"variable.H\"" >> $hackThisHeader
            echo "#endif" >> $hackThisHeader

            rm ${hackThisHeader}.tmp
        )
    fi
fi


wmake $targetType general
wmake $targetType interRegion
wmake $targetType rotorDisk
#wmake $targetType propellerDisk

#------------------------------------------------------------------------------
