#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

if ! onWin; then

wmake $targetType phaseSystem
wmake $targetType interfacialModels
wmake $targetType populationBalance
wmake $targetType momentumTransportModels
wmake $targetType thermophysicalTransportModels
wmake $targetType reactions
wmake $targetType phaseSystems

wmake $targetType

wmake $targetType fvModels
wmake $targetType functionObjects

else

    wmakeLnInclude interfacialModels

    set +x

    echo "Library stub stack is currently being built at" \
         "multiphaseEuler..."
    # Going to ommit the first build pass, as it will give a few errors, but
    # it's the second pass that matters.
    (

        for libitem in $(grep -h "LIB =" */Make/files | sed 's=.*/=='); do
            if [ ! -e "$FOAM_LIBBIN/${libitem}.a" ]; then
                cp $FOAM_LIBBIN/libstubLibrary.a $FOAM_LIBBIN/${libitem}.a

                if [ -e "$FOAM_LIBBIN/${libitem}.dll" ]; then
                    rm $FOAM_LIBBIN/${libitem}.dll
                fi
            fi
        done
  
        export WM_CONTINUE_ON_ERROR=1
        set +e
  
        wmake $targetType phaseSystem
        wmake $targetType interfacialModels
        wmake $targetType populationBalance
        wmake $targetType momentumTransportModels
        wmake $targetType thermophysicalTransportModels
        wmake $targetType reactions
        wmake $targetType phaseSystems

        wmake $targetType fvModels
        wmake $targetType functionObjects
  
        exit 0

    ) 2> /dev/null

    echo "Library stub stack is done being built at" \
         "multiphaseEulerFoam."

    # Now going to do the second and final linking step.
    set -x

    wmake $targetType phaseSystem
    wmake $targetType interfacialModels
    wmake $targetType populationBalance
    wmake $targetType momentumTransportModels
    wmake $targetType thermophysicalTransportModels
    wmake $targetType reactions
    wmake $targetType phaseSystems

    wmake $targetType

    wmake $targetType fvModels
    wmake $targetType functionObjects

fi

#------------------------------------------------------------------------------
