#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

if ! onWin; then

wmakeLnInclude interfacialModels
wmake libso twoPhaseSystem
wmake libso interfacialModels
wmake libso phaseCompressibleTurbulenceModels
wmake

else

wmakeLnInclude interfacialModels

set +x
# Going to ommit the first build loop, as it will give a few errors, but it's
# the second loop that matters.
(

  for libitem in $(grep -h "LIB =" */Make/files | sed 's=.*/=='); do
    if [ ! -e "$FOAM_LIBBIN/${libitem}.a" ]; then
      cp $FOAM_LIBBIN/libstubLibrary.a $FOAM_LIBBIN/${libitem}.a
    fi
    if [ -e "$FOAM_LIBBIN/${libitem}.dll" ]; then
      rm $FOAM_LIBBIN/${libitem}.dll
    fi
  done

  export WM_CONTINUE_ON_ERROR=1
  set +e

  set -x
  wmake libso twoPhaseSystem
  wmake libso interfacialModels
  wmake libso phaseCompressibleTurbulenceModels
  set +x

  exit 0

) 2> /dev/null

# Now going to do the second and final linking step.
set -x

wmake libso twoPhaseSystem
wmake libso interfacialModels
wmake libso phaseCompressibleTurbulenceModels

wmake

fi

# ----------------------------------------------------------------- end-of-file
