#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

[ -d "$WM_PROJECT_DIR" ] || {
    echo "    Error: WM_PROJECT_DIR directory does not exist"
    echo "        Check the OpenFOAM entries in your dot-files and source them."
    echo "        WM_PROJECT_DIR=$WM_PROJECT_DIR"
    exit 1
}

usage() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

usage: ${0##*/} [OPTION] <path-1> <path-2> ...
options:
  -online    use the links to the Github repositories instead of the local source code
  -help

USAGE
    exit 1
}

defineURL() {

  case "$WM_PROJECT_VERSION" in
  [0-9].x)
    FOAM_BRANCH_NAME="master"
    FOAM_REPO_VERSION="$WM_PROJECT-$WM_PROJECT_VERSION"
    ;;
  [0-9].[0-9])
    FOAM_BRANCH_NAME="version-$WM_PROJECT_VERSION"
    FOAM_REPO_VERSION="$WM_PROJECT-${WM_PROJECT_VERSION%.*}.x"
    ;;
  *)
    FOAM_BRANCH_NAME="master"
    FOAM_REPO_VERSION="$WM_PROJECT-$WM_PROJECT_VERSION"
    ;;
  esac

  export FOAM_BASE_REPO="https://github.com/$WM_PROJECT/$FOAM_REPO_VERSION"
  export FOAM_ONLINE_REPO="$FOAM_BASE_REPO/tree/$FOAM_BRANCH_NAME"
}

# parse options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help)
        usage
        ;;
    -online)
        defineURL
        shift
        ;;
    -*)
        usage "unknown option/argument: '$*'"
        ;;
    *)
        inputDirs="$inputDirs $1"
        shift
        ;;
    esac
done

#------------------------------------------------------------------------------

set -x

for folder in html latex man qt_qch; do
  # remove $folder directory in background
  if [ -d "$folder" ]; then
    mv $folder ${folder}-stagedRemove$$ 2> /dev/null
    rm -rf ${folder}-stagedRemove$$ >/dev/null 2>&1 &
  fi
done

# format the input directories
[ -z "$inputDirs" ] || inputDirs="INPUT=$inputDirs"

# ensure that created files are readable by everyone
umask 22
if isMinGW; then

  mkdir html
  cp -r css html/
  cp *.png html/

  if onWin; then
    doxygen DoxyfileMinGWQtWin
  else
    doxygen DoxyfileMinGWQt
  fi

else

(cat Doxyfile; echo "$inputDirs") | doxygen -

fi

# fix permissions (NB: '+X' and not '+x'!)
for folder in html latex man; do
  [ -d "$folder" ] && chmod -R a+rX $folder 2>/dev/null
done

echo
echo "Done doxygen"
echo

echo
echo "Generating Qt collection..."
echo

[ ! -e qt_qch ] && mkdir qt_qch

sed -e "s=WM_PROJECT_VERSION=$WM_PROJECT_VERSION=" openfoam-code.qhcp > \
    qt_qch/openfoam-code-$WM_PROJECT_VERSION.qhcp

cd qt_qch
qcollectiongenerator openfoam-code-$WM_PROJECT_VERSION.qhcp \
    -o openfoam-code-$WM_PROJECT_VERSION.qhc
cd ..

echo
echo "Done Qt collection generation."
echo

#------------------------------------------------------------------------------
