#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

[ -d "$WM_PROJECT_DIR" ] || {
    echo "Error: WM_PROJECT_DIR directory does not exist"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    echo "    WM_PROJECT_DIR=$WM_PROJECT_DIR"
    exit 1
}

set -x

for folder in html latex man qt_qch; do
  # remove $folder directory in background
  if [ -d "$folder" ]; then
    mv $folder ${folder}-stagedRemove$$ 2> /dev/null
    rm -rf ${folder}-stagedRemove$$ >/dev/null 2>&1 &
  fi
done

# ensure that created files are readable by everyone
umask 22
if isMinGW; then

  mkdir html
  cp -r css html/
  cp *.png html/

  if onWin; then
    doxygen DoxyfileMinGWQtWin
  else
    doxygen DoxyfileMinGWQt
  fi

else

doxygen

fi

# fix permissions (NB: '+X' and not '+x'!)
for folder in html latex man; do
  [ -d "$folder" ] && chmod -R a+rX $folder 2>/dev/null
done

echo
echo "Done doxygen"
echo


echo
echo "Generating Qt collection..."
echo

[ ! -e qt_qch ] && mkdir qt_qch

sed -e "s=WM_PROJECT_VERSION=$WM_PROJECT_VERSION=" openfoam-code.qhcp > \
    qt_qch/openfoam-code-$WM_PROJECT_VERSION.qhcp

cd qt_qch
qcollectiongenerator openfoam-code-$WM_PROJECT_VERSION.qhcp \
    -o openfoam-code-$WM_PROJECT_VERSION.qhc
cd ..

echo
echo "Done Qt collection generation."
echo

# ----------------------------------------------------------------- end-of-file
