#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

if ! isMinGW; then

wmake $targetType multiphaseSystem
wmake $targetType multiphaseCompressibleTurbulenceModels
wmake

else

    set +x

    echo "Library stub stack is currently being built at" \
         "reactingMultiphaseEulerFoam..."

    # Going to ommit the first build loop, as it will give a few errors, but
    # it's the second loop that matters.
    (
        export WM_CONTINUE_ON_ERROR=1
        set +e

        (find .. -name "Make.multiphase" -type d ; \
         find . -name "Make.win" -type d) | \
            xargs -I {} grep -h "LIB =" {}/files | sed 's=.*/==' | \
            while read libitem
        do
            if [ ! -e "$FOAM_LIBBIN/${libitem}.a" ]; then
              cp $FOAM_LIBBIN/libstubLibrary.a $FOAM_LIBBIN/${libitem}.a
            fi
            if [ -e "$FOAM_LIBBIN/${libitem}.dll" ]; then
              rm $FOAM_LIBBIN/${libitem}.dll
            fi
        done

        for folder in \
            ../phaseSystems/ \
            ../interfacialModels/ \
            ../interfacialCompositionModels/
        do
            folder=$(wdep $folder| \
                     sed -e 's=\.dep$==')
            for file in sourceFiles variables options
            do
                rm $folder$file
            done
        done

        wmake libso ../phaseSystems Make.multiphase
        wmake libso ../interfacialModels Make.multiphase
        wmake libso ../interfacialCompositionModels Make.multiphase

        wmake libso multiphaseSystem Make.win
        wmake libso multiphaseCompressibleTurbulenceModels Make.win

        exit 0

    ) > /dev/null 2>&1

    echo "Library stub stack is done being built at" \
         "reactingMultiphaseEulerFoam."

    set -x

    wmake libso ../phaseSystems Make.multiphase
    wmake libso ../interfacialModels Make.multiphase
    wmake libso ../interfacialCompositionModels Make.multiphase

    wmake libso multiphaseSystem Make.win
    wmake libso multiphaseCompressibleTurbulenceModels Make.win

    wmake

fi

#------------------------------------------------------------------------------
