#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

if ! onWin; then

wclean libso multiphaseSystem
wclean libso multiphaseCompressibleTurbulenceModels
wclean

else

    wclean libso ../phaseSystems Make.multiphase
    wclean libso ../interfacialModels Make.multiphase
    wclean libso ../interfacialCompositionModels Make.multiphase

    wclean libso multiphaseSystem Make.win
    wclean libso multiphaseCompressibleTurbulenceModels Make.win

    wclean

fi

#------------------------------------------------------------------------------
