#!/bin/sh
#------------------------------------------------------------------------------
# License
#
#    Copyright (C) 2011-2014 blueCAPE Lda
#
#    This file is part of blueCAPE's unofficial mingw patches for OpenFOAM.
#    For more information about these patches, visit:
#         http://bluecfd.com/Core
#
#    This file is a derivative work of OpenFOAM.
#
#    OpenFOAM is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#    for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     Allwmake
#
# Description
#     Build script for the tutorials that have Make folders.
#
#------------------------------------------------------------------------------

#run only from the tutorials folder
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

find . -name Make | \
while read makeFolder; do

  #get the parent folder of Make
  folderToBuild=`echo $makeFolder | sed -e 's=/Make$=='`

  wmake all $folderToBuild

  if isMinGW; then
    wmakeVerifyExeDependencies $folderToBuild || wmake all $folderToBuild
  fi

done
