#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-lib makeType' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake $makeType cloud
wmake $makeType field
wmake $makeType forces
wmake $makeType fvTools
wmake $makeType IO
wmake $makeType jobControl
wmake $makeType systemCall
wmake $makeType utilities

# ----------------------------------------------------------------- end-of-file
