#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

if [ -n "$CGAL_ARCH_PATH" -a -d "$CGAL_ARCH_PATH" ] || [ "$CGAL_ARCH_PATH" = "system" ]
then
    wmake libso conformalVoronoiMesh
    wmake
    #wmake foamyHexMeshBackgroundMesh
    #(cd foamyHexMeshSurfaceSimplify && ./Allwmake)
    #wmake cellSizeAndAlignmentGrid
fi

# ----------------------------------------------------------------- end-of-file
