#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments


if isMinGW && [ -z "$WM_PSTREAMLINK" ]; then
    export targetType="lib"
fi

wmake $targetType dummy

case "$WM_MPLIB" in
*MPI*)
    wmake $targetType mpi
    ;;
esac


#------------------------------------------------------------------------------
