#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-lib makeType' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

#
# define how to create an mpi-versioned library of $makeType
# compile into qualified directory
# use sentinel file to handle version changes
#
wmakeMpiLib()
{
    set +x
    export makeType
    for libName
    do
    (
        export WM_OPTIONS_LOCAL="$WM_OPTIONS$WM_MPLIB"
        whichmpi="$libName/Make/$WM_OPTIONS_LOCAL/using:$FOAM_MPI"
        [ -e "$whichmpi" ] || wclean $libName
        echo "wmake $buildMode $libName"
        wmake $buildMode $libName
        touch "$whichmpi"
    )
    done
    set -x
}

set -x

buildMode=$makeType

if isMinGW; then
  if [ "$WM_PSTREAMLINK" = "LINKTOPSTREAM" ]; then
    buildMode=$makeType
  else
    buildMode="lib"
  fi
fi

wmake $buildMode dummy

case "$WM_MPLIB" in
*MPI*)
    set +x
    echo
    echo "Note: ignore spurious warnings about missing mpicxx.h headers"
    echo
    wmakeMpiLib mpi
    ;;

#GAMMA)
#    wmake $makeType gamma
#    ;;
esac


# ----------------------------------------------------------------- end-of-file
