#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Parse arguments for compilation (at least for error catching)
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

unset COMP_FLAGS LINK_FLAGS

#
# use readline if available
#

if ! isMinGW && [ -f /usr/include/readline/readline.h ]
then
    echo "    found <readline/readline.h>  --  enabling readline support."
    export COMP_FLAGS="-DHAS_READLINE"

    # readline may require ncurses
    if [ -f /usr/include/ncurses/ncurses.h ]
    then
        echo "    found <ncurses/ncurses.h>  --  maybe required by readline."
        export LINK_FLAGS="-lreadline -lncurses"
    else
        export LINK_FLAGS="-lreadline"
    fi
elif onWin && [ -f /mingw64/include/readline/readline.h ]
then
    echo "    found <readline/readline.h>  --  enabling readline support."
    export COMP_FLAGS="-DHAS_READLINE"
    export LINK_FLAGS="-lreadline"

fi

wmake $targetType

#------------------------------------------------------------------------------
