#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

if ! onWin; then

wmake $targetType phaseSystems
wmake $targetType interfacialModels
wmake $targetType interfacialCompositionModels
wmake $targetType multiphaseCompressibleMomentumTransportModels
wmake $targetType multiphaseThermophysicalTransportModels
multiphaseEulerFoam/Allwmake $targetType $*
wmake $targetType functionObjects

else

    # TODO: Pending revision
    wmake $targetType phaseSystems
    wmakeLnInclude interfacialModels

    set +x

    echo "Library stub stack is currently being built at" \
         "multiphaseEulerFoam..."
    # Going to ommit the first build pass, as it will give a few errors, but
    # it's the second pass that matters.
    (

      for libitem in $(grep -h "LIB =" */Make/files | sed 's=.*/=='); do
        if [ ! -e "$FOAM_LIBBIN/${libitem}.a" ]; then
          cp $FOAM_LIBBIN/libstubLibrary.a $FOAM_LIBBIN/${libitem}.a
        fi
        if [ -e "$FOAM_LIBBIN/${libitem}.dll" ]; then
          rm $FOAM_LIBBIN/${libitem}.dll
        fi
      done

      export WM_CONTINUE_ON_ERROR=1
      set +e

      wmake libso multiphaseSystem
      wmake libso interfacialModels

      exit 0

    ) > /dev/null 2>&1

    echo "Library stub stack is done being built at" \
         "multiphaseEulerFoam."

    # Now going to do the second and final linking step.
    set -x

    wmake libso multiphaseSystem
    wmake libso interfacialModels

    wmake

fi

#------------------------------------------------------------------------------
