#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wmake libso tabulatedWallFunction
wmake

# ----------------------------------------------------------------- end-of-file
