#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

if ! onWin; then

wclean libso phaseSystems
wclean libso interfacialModels
wclean libso interfacialCompositionModels
reactingTwoPhaseEulerFoam/Allwclean
reactingMultiphaseEulerFoam/Allwclean


    # The libraries are not built here, they are built differently on Windows
    ##wclean libso phaseSystems
    ##wclean libso interfacialModels
    ##wclean libso interfacialCompositionModels

    reactingTwoPhaseEulerFoam/Allwclean
    reactingMultiphaseEulerFoam/Allwclean

fi

#------------------------------------------------------------------------------
