#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

if ! onWin; then

wmake $targetType phaseSystems
wmake $targetType interfacialModels
wmake $targetType interfacialCompositionModels
wmake $targetType derivedFvPatchFields
reactingTwoPhaseEulerFoam/Allwmake $targetType $*
reactingMultiphaseEulerFoam/Allwmake $targetType $*
wmake $targetType functionObjects

else

    wmakeLnInclude interfacialModels
    wmakeLnInclude interfacialCompositionModels
    wmakeLnInclude phaseSystems

    # These libraries are not built here, because we have to build one copy
    # per solver, due to cyclic dependencies with their own turbulence models.

    ## wmake libso phaseSystems
    ## wmake libso interfacialModels
    ## wmake libso interfacialCompositionModels

    wmake $targetType derivedFvPatchFields
    wmake $targetType functionObjects

    reactingTwoPhaseEulerFoam/Allwmake
    reactingMultiphaseEulerFoam/Allwmake

fi

#------------------------------------------------------------------------------
