#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

if ! isMinGW; then

wmakeLnInclude interfacialModels
wmakeLnInclude interfacialCompositionModels
wmake $targetType phaseSystems
wmake $targetType interfacialModels
wmake $targetType interfacialCompositionModels
reactingTwoPhaseEulerFoam/Allwmake $*
reactingMultiphaseEulerFoam/Allwmake $*

else

    wmakeLnInclude interfacialModels
    wmakeLnInclude interfacialCompositionModels
    wmakeLnInclude phaseSystems

    # These libraries are not built here, because we have to build one copy
    # per solver, due to cyclic dependencies with their own turbulence models.

    ## wmake libso phaseSystems
    ## wmake libso interfacialModels
    ## wmake libso interfacialCompositionModels

    reactingTwoPhaseEulerFoam/Allwmake
    reactingMultiphaseEulerFoam/Allwmake

fi

#------------------------------------------------------------------------------
