#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

set -x

if [ -z "$WM_MPLIB" ]; then
    exit 0
fi

wmake decomposePar
wmake reconstructPar
wmake redistributePar
