#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

refineMeshByCellSet()
{
   while [ $# -ge 1 ]
   do
      if [ ! -e log.refineMesh.$1 ]
      then
          echo "creating cell set for primary zone - $1"
          cp system/topoSetDict.$1 system/topoSetDict
          topoSet > log.topoSet.$1 2>&1

          echo "refining primary zone - $1"
          refineMesh -dict system/refineMeshDict -overwrite > log.refineMesh.$1 2>&1
      fi
      shift
   done
}

#First check if the 2D case has been properly executed
HADTORUN2D=""
if [ -z "$(ls ../throttle/[1-9]* 2> /dev/null)" ]; then
   echo "The 2D case has no results, therefore will have at least run one iteration."
   HADTORUN2D="yes"
   ../throttle/Allrun
   echo "2D case has been executed (did not check for success)."
fi

cp -r 0.org 0

runApplication blockMesh
refineMeshByCellSet 1 2 3

#echo "mapping fields from 2D throttle case"
#runApplication mapFields ../throttle -sourceTime latestTime

runApplication decomposePar
runParallel $application 4
runApplication reconstructPar

if [ -n "$HADTORUN2D" ]; then
  ../throttle/Allclean
fi

# ----------------------------------------------------------------- end-of-file
